# Generated by Django 4.2.1 on 2023-05-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='formula',
            field=models.CharField(max_length=255, verbose_name='Формула'),
        ),
    ]
