# Generated by Django 4.1.3 on 2023-05-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_history_formula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scientist',
            name='plot_path',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Путь до графика'),
        ),
    ]
