# Generated by Django 4.2.1 on 2023-05-19 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Science',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, unique=True, verbose_name='Название науки')),
                ('content', models.TextField(verbose_name='О науке')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг науки')),
            ],
            options={
                'unique_together': {('title', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название раздела')),
                ('content', models.TextField(verbose_name='О разделе')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг раздела')),
                ('science', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='science.science')),
            ],
            options={
                'unique_together': {('title', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Название формулы')),
                ('content', models.TextField(verbose_name='О формуле')),
                ('formula', models.CharField(max_length=255, unique=True, verbose_name='Формула')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг формулы')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='science.category')),
            ],
            options={
                'unique_together': {('title', 'slug', 'formula')},
            },
        ),
    ]
